version: '3.8'
services:
  app:
    container_name: "${APP_NAME}"
    build: 
      context: ../../
      dockerfile: docker-front/production/Dockerfile
    ports:
      - "${APP_PORT:-80}:${NGINX_PORT:-80}"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - APP_ENV=${APP_ENV:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3 